# Generated by Django 4.2.2 on 2023-06-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLibro', models.IntegerField(verbose_name='IdLibro')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN')),
                ('numpags', models.IntegerField(verbose_name='NumPags')),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.IntegerField(verbose_name='IdUsuario')),
                ('numusuario', models.IntegerField(verbose_name='NumUsuario')),
                ('nif', models.CharField(max_length=20, verbose_name='NIF')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprestamo', models.IntegerField(verbose_name='IdPrestamo')),
                ('fecprestamo', models.DateField(auto_now=True)),
                ('fecdevolucion', models.DateField()),
                ('idlibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.usuario')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idautor', models.IntegerField(verbose_name='IdAutor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('idlibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
    ]
